In [54]:
import numpy as np
from keras.utils import np_utils

half_batch = 16
num_classes = 2
label_gla_nor = np.array([[9],[1],[6],[1],[0],[0],[0],[5],[1],[0],[0],[1],[1],[0],[1],[1]])


In [55]:
labels = np_utils.to_categorical(label_gla_nor, num_classes=11)
print(labels)
fake_labels = np_utils.to_categorical(np.full((half_batch, 1), 10), num_classes=11)
print(fake_labels)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0

In [48]:
batch_fake = np.ones((half_batch, 1))*2
batch_fake = np_utils.to_categorical(batch_fake, num_classes=num_classes + 1)
#batch_fake[:] = 0.2

print(batch_fake)



[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [45]:
batch_labels = np_utils.to_categorical(label_gla_nor, num_classes=num_classes+1)
for j in range(half_batch):
    batch_labels[j][2] = 0.8

batch_labels[batch_labels == 1 ] = 0.3
batch_labels[batch_labels == 0] = 0.7



print(batch_labels)



[[0.3 0.7 0.8]
 [0.7 0.3 0.8]
 [0.3 0.7 0.8]
 [0.7 0.3 0.8]
 [0.3 0.7 0.8]
 [0.3 0.7 0.8]
 [0.3 0.7 0.8]
 [0.3 0.7 0.8]
 [0.7 0.3 0.8]
 [0.3 0.7 0.8]
 [0.3 0.7 0.8]
 [0.7 0.3 0.8]
 [0.7 0.3 0.8]
 [0.3 0.7 0.8]
 [0.7 0.3 0.8]
 [0.7 0.3 0.8]]


In [41]:
batch_labels = np.concatenate((batch_labels, batch_fake))
print(batch_labels)

[[0.7 0.3 0.8]
 [0.3 0.7 0.8]
 [0.7 0.3 0.8]
 [0.3 0.7 0.8]
 [0.7 0.3 0.8]
 [0.7 0.3 0.8]
 [0.7 0.3 0.8]
 [0.7 0.3 0.8]
 [0.3 0.7 0.8]
 [0.7 0.3 0.8]
 [0.7 0.3 0.8]
 [0.3 0.7 0.8]
 [0.3 0.7 0.8]
 [0.7 0.3 0.8]
 [0.3 0.7 0.8]
 [0.3 0.7 0.8]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]]


In [29]:
fake_labels = np_utils.to_categorical(np.full((half_batch, 1), 3), num_classes=4)
print(fake_labels)

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [62]:
print('%s' % float('%.3g' % 956/2358))

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [ ]:
np.array()